# Generated by Django 5.2.11 on 2026-02-10 17:37

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='doc_type',
            field=models.CharField(choices=[('metodologico', 'Technical document'), ('datos', 'Statistics and reports'), ('otro', 'Viewers')], db_index=True, default='metodologico', max_length=30),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='image',
            field=models.ImageField(blank=True, help_text='Portada (imagen principal del trabajo). Se recomienda PNG/JPG nítido; ideal sin fondo. Usa un formato apaisado si es posible (ej.: 1200×600 o 1600×800) para buena vista en el carrusel.', null=True, upload_to=catalogo.models.upload_trabajo_image_to),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Miniatura/thumbnail (URL). Se recomienda imagen ligera y clara; ideal sin fondo. Tamaño sugerido: 600×600 o 800×800 (cuadrada) o 800×450 (apaisada), según tu diseño.'),
        ),
    ]
