# Generated by Django 5.2.11 on 2026-02-11 20:23

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_documento_doc_type_alter_trabajo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(blank=True, null=True, storage=catalogo.models.DocumentRawStorage(), upload_to=catalogo.models.upload_document_to),
        ),
    ]
