# Generated by Django 5.2.11 on 2026-02-14 18:02

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_documento_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ('-published_at', '-created_at')},
        ),
        migrations.AlterField(
            model_name='documento',
            name='doc_type',
            field=models.CharField(choices=[('metodologico', 'Technical document'), ('datos', 'Statistics and reports'), ('otro', 'Viewers')], default='metodologico', max_length=30),
        ),
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=catalogo.models.DocumentRawStorage(), upload_to=catalogo.models.upload_document_to),
        ),
        migrations.AlterField(
            model_name='documento',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=catalogo.models.upload_trabajo_image_to),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
