# portal/settings.py
"""
Django settings for portal project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-0jc^$hz*tonn)au1wzj6ady8e12_rg=wo3-63l5v=r-do468*!"
DEBUG = True
ALLOWED_HOSTS: list[str] = []


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your apps
    "core",
    "catalogo.apps.CatalogoConfig",

    # Dev utilities
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",

    # i18n must be enabled here
    "django.middleware.locale.LocaleMiddleware",

    # Force admin UI in English
    "portal.middleware.AdminEnglishMiddleware",

    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "portal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Inject Areas into navbar dropdown globally
                "catalogo.context_processors.nav_areas",
            ],
        },
    },
]

WSGI_APPLICATION = "portal.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# -----------------------------
# Internationalization (i18n)
# -----------------------------
USE_I18N = True
USE_TZ = True
TIME_ZONE = "UTC"

# Public site default language
LANGUAGE_CODE = "es"

LANGUAGES = [
    ("es", "Español"),
    ("en", "English"),
]

# Keep locale files at project level
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files
STATIC_URL = "/static/"

# Media
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
